/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ComputadorController;
import utils.JtableController;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sillas.clpinto
 */
public final class ConsultarView extends javax.swing.JFrame {
    /**
     * Creates new form GravarView
     */
    public ConsultarView() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        JtableController.carregarTabela(tblComputador, txtFiltrarComputador.getText().trim()); //preenchendo tabela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComputador = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFiltrarComputador = new javax.swing.JTextField();
        btnAlterarComputador = new javax.swing.JButton();
        btnRemoverComputador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Computador"));

        tblComputador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Marca", "HD", "Processador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblComputador.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblComputador);

        jLabel1.setText("Filtrar por marca:");

        txtFiltrarComputador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltrarComputadorKeyReleased(evt);
            }
        });

        btnAlterarComputador.setText("Alterar");
        btnAlterarComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarComputadorActionPerformed(evt);
            }
        });

        btnRemoverComputador.setText("Remover");
        btnRemoverComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverComputadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltrarComputador))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlterarComputador, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverComputador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFiltrarComputador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarComputador)
                    .addComponent(btnRemoverComputador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltrarComputadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarComputadorKeyReleased
//        JtableController.carregarTabela(tblComputador, txtFiltrarComputador.getText().trim()); //preencher tabela ao liberar alguma tecla
        TableRowSorter<TableModel> filtro = new TableRowSorter<>((DefaultTableModel)tblComputador.getModel());
        filtro.setRowFilter(RowFilter.regexFilter(txtFiltrarComputador.getText(), 1));
        
        tblComputador.setRowSorter(filtro);
    }//GEN-LAST:event_txtFiltrarComputadorKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        GravarView view = new GravarView();
        view.setVisible(true); //reabrir tela de cadastro ao fechar esta
    }//GEN-LAST:event_formWindowClosed

    private void btnAlterarComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarComputadorActionPerformed
        int[] indices = tblComputador.getSelectedRows(); //obtendo indices das linhas selecionadas
        
        if (indices.length == 1) { //caso tenha apenas uma linhas selecionada
            if (ComputadorController.alterarComputador(indices[0], tblComputador)) { //realizando update atraves das alteracoes da tabela
                JOptionPane.showMessageDialog(this, "Dados alterados com sucesso");
                JtableController.carregarTabela(tblComputador, txtFiltrarComputador.getText()); 
            } else {
                JOptionPane.showMessageDialog(this, "Nao foi possivel alterar os dados selecionados");
            }
        } else if (indices.length > 1) {
            JOptionPane.showMessageDialog(this, "Soh eh possivel alterar uma linha por vez");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha");
        }
    }//GEN-LAST:event_btnAlterarComputadorActionPerformed

    private void btnRemoverComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverComputadorActionPerformed
        int[] indices = tblComputador.getSelectedRows(); //obtendo indices de todas as linhas selecionadas
        
        if (indices.length > 0) { //verificando se alguma linha foi selecionada 
            for (int indice : indices) { //removendo dados de todas as linhas selecionadas
                if (ComputadorController.removerComputador(JtableController.getLinhaSelecionada(indice, tblComputador).getId())) { //obtendo id da linha selecionada e executando delete
                    JOptionPane.showMessageDialog(this, "Dados da linha: "+ (indice + 1) +" removidos com sucesso");
                } else {
                    JOptionPane.showMessageDialog(this, "Nao foi possivel remover os dados selecionados da linha: " + (indice + 1));
                }   
            }
            JtableController.carregarTabela(tblComputador, txtFiltrarComputador.getText()); 
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma ou mais linhas");
        }
    }//GEN-LAST:event_btnRemoverComputadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarComputador;
    private javax.swing.JButton btnRemoverComputador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComputador;
    private javax.swing.JTextField txtFiltrarComputador;
    // End of variables declaration//GEN-END:variables
}